export const invoice = [
	{
		id: 'RT3080',
		slug: 'rt3080',
		createdAt: '2021-08-18',
		paymentDue: '2021-08-19',
		description: 'Re-branding',
		paymentTerms: 1,
		clientName: 'Jensen Huang',
		clientEmail: 'jensenh@mail.com',
		status: 'paid',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '106 Kendell Street',
			cityTwo: 'Sharrington',
			postCodeTwo: 'NR24 5WQ',
			countryTwo: 'United Kingdom',
		},
		items: [
			{
				name: 'Brand Guidelines',
				quantity: 1,
				price: 1800.9,
				total: 1800.9,
			},
		],
		total: 1800.9,
	},
	{
		id: 'XM9141',
		slug: 'xm9141',
		createdAt: '2021-08-21',
		paymentDue: '2021-09-20',
		description: 'Graphic Design',
		paymentTerms: 30,
		clientName: 'Alex Grim',
		clientEmail: 'alexgrim@mail.com',
		status: 'pending',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '84 Church Way',
			cityTwo: 'Bradford',
			postCodeTwo: 'BD1 9PB',
			countryTwo: 'United Kingdom',
		},
		items: [
			{
				name: 'Banner Design',
				quantity: 1,
				price: 156.0,
				total: 156.0,
			},
			{
				name: 'Email Design',
				quantity: 2,
				price: 200.0,
				total: 400.0,
			},
		],
		total: 556.0,
	},
	{
		id: 'RG0314',
		slug: 'rg0314',
		createdAt: '2021-09-24',
		paymentDue: '2021-10-01',
		description: 'Website Redesign',
		paymentTerms: 7,
		clientName: 'John Morrison',
		clientEmail: 'jm@myco.com',
		status: 'paid',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '79 Dover Road',
			cityTwo: 'Westhall',
			postCodeTwo: 'IP19 3PF',
			countryTwo: 'United Kingdom',
		},
		items: [
			{
				name: 'Website Redesign',
				quantity: 1,
				price: 14002.33,
				total: 14002.33,
			},
		],
		total: 14002.33,
	},
	{
		id: 'RT2080',
		slug: 'rt2080',
		createdAt: '2021-10-11',
		paymentDue: '2021-10-12',
		description: 'Logo Concept',
		paymentTerms: 1,
		clientName: 'Alysa Werner',
		clientEmail: 'alysa@email.co.uk',
		status: 'pending',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '63 Warwick Road',
			cityTwo: 'Carlisle',
			postCodeTwo: 'CA20 2TG',
			countryTwo: 'United Kingdom',
		},
		items: [
			{
				name: 'Logo Sketches',
				quantity: 1,
				price: 102.04,
				total: 102.04,
			},
		],
		total: 102.04,
	},
	{
		id: 'AA1449',
		slug: 'aa1449',
		createdAt: '2021-10-7',
		paymentDue: '2021-10-14',
		description: 'Re-branding',
		paymentTerms: 7,
		clientName: 'Mellisa Clarke',
		clientEmail: 'mellisa.clarke@example.com',
		status: 'pending',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '46 Abbey Row',
			cityTwo: 'Cambridge',
			postCodeTwo: 'CB5 6EG',
			countryTwo: 'United Kingdom',
		},
		items: [
			{
				name: 'New Logo',
				quantity: 1,
				price: 1532.33,
				total: 1532.33,
			},
			{
				name: 'Brand Guidelines',
				quantity: 1,
				price: 2500.0,
				total: 2500.0,
			},
		],
		total: 4032.33,
	},
	{
		id: 'TY9141',
		slug: 'ty9141',
		createdAt: '2021-10-01',
		paymentDue: '2021-10-31',
		description: 'Landing Page Design',
		paymentTerms: 30,
		clientName: 'Thomas Wayne',
		clientEmail: 'thomas@dc.com',
		status: 'pending',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '3964  Queens Lane',
			cityTwo: 'Gotham',
			postCodeTwo: '60457',
			countryTwo: 'United States of America',
		},
		items: [
			{
				name: 'Web Design',
				quantity: 1,
				price: 6155.91,
				total: 6155.91,
			},
		],
		total: 6155.91,
	},
	{
		id: 'FV2353',
		slug: 'fv 2353',
		createdAt: '2021-11-05',
		paymentDue: '2021-11-12',
		description: 'Logo Re-design',
		paymentTerms: 7,
		clientName: 'Anita Wainwright',
		clientEmail: '',
		status: 'draft',
		senderAddress: {
			streetOne: '19 Union Terrace',
			cityOne: 'London',
			postCodeOne: 'E1 3EZ',
			countryOne: 'United Kingdom',
		},
		clientAddress: {
			streetTwo: '',
			cityTwo: '',
			postCodeTwo: '',
			countryTwo: '',
		},
		items: [
			{
				name: 'Logo Re-design',
				quantity: 1,
				price: 3102.04,
				total: 3102.04,
			},
		],
		total: 3102.04,
	},
];
