import Head from 'next/head'
import Header from '../src/components/Header'
import SideBar from '../src/components/SideBar'
import type { NextPage } from 'next';
import Form from '../src/components/form/Form';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<main>
        <SideBar />
        <div className="container">
          <div className="main__flex">
            <Header />
          </div>
          <Form />
        </div>
			</main>
    </div>
  )
}

export default Home;
