import React, { useState } from 'react'
import Head from 'next/head'
import Header from '../src/components/Header'
import SideBar from '../src/components/SideBar'
import type { NextPage } from 'next';
import Form from '../src/components/form/Form';
import Invoices from '../src/components/invoices/Invoices';

interface HomeProps {
  toggleTheme: () => void;
  invoiceOpen: boolean;
}

const Home: NextPage<HomeProps> = () => {
  const [theme, setTheme] = useState('light');
  const [invoiceOpen, setInvoiceOpen] = useState(false);
  const [sideBarIcon, setSideBarIcon] = useState(false)
  
  const toggleTheme = () => {
    setTheme(theme === 'light' ? 'dark' : 'light');
    setSideBarIcon(!sideBarIcon)
  }
  
  const openFilter = () => { 
    setInvoiceOpen(!invoiceOpen)
  }

  const discardForm = (e: any) => { 
    e.preventDefault();
    setInvoiceOpen(invoiceOpen)
    console.log("clicked");
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<main className={theme}>
        <SideBar sideBarIcon={sideBarIcon} theme={theme} toggleTheme={toggleTheme} />
        {invoiceOpen ? <div className='form__overlay'></div> : null}
        {invoiceOpen
          ? 
          <Form discardForm={discardForm} invoiceOpen={invoiceOpen} />
          :
          null
        }
        <div className="container">
          <div className="main__flex">
            <Header invoiceOpen={invoiceOpen} setInvoiceOpen={setInvoiceOpen} openFilter={openFilter} />
          </div>
          <Invoices/>
        </div>
			</main>
    </div>
  )
}

export default Home;
